# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ehr1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('why', models.TextField()),
                ('when', models.TextField()),
                ('medication', models.CharField(max_length=50)),
                ('allergic', models.CharField(max_length=50)),
                ('highBloodPressure', models.BooleanField(default=False)),
                ('heartDisease', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('thyroid', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('highCholesterol', models.BooleanField(default=False)),
                ('appointmentDate', models.DateTimeField(default=False)),
            ],
        ),
    ]
